CREATE TABLE IF NOT EXISTS configuraciones_sistema (
    id_configuracion integer GENERATED BY DEFAULT AS IDENTITY,
    monto_minimo_contrato numeric NOT NULL,
    horario_inicio_minutos integer NOT NULL,
    horario_fin_minutos integer NOT NULL,
    nombre_jefe_carrera text NOT NULL,
    firma_jefe_carrera_base64 text NOT NULL,
    tiempo_minimo_reserva_minutos integer NOT NULL,
    tiempo_recordatorio_previo_minutos integer NOT NULL,
    minutos_gracia_atraso integer NOT NULL,
    estado_eliminado boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_configuraciones_sistema PRIMARY KEY (id_configuracion)
);
