export interface PrestamoApiItem {
  Id: number;
  CarnetUsuario: string | null;
  NombreUsuario: string | null;
  ApellidoPaternoUsuario: string | null;
  TelefonoUsuario: string | null;
  NombreGrupoEquipo: string | null;
  CodigoImt: string | null;
  CodigoUcb?: string | null;
  NumeroSerial?: string | null;
  FechaSolicitud: string | Date | null;
  FechaPrestamoEsperada: string | Date | null;
  FechaPrestamo: string | Date | null;
  FechaDevolucionEsperada: string | Date | null;
  FechaDevolucion: string | Date | null;
  Observacion: string | null;
  MotivoRechazo?: string | null;
  AutorizadoPor?: string | null;
  EntregadoPor?: string | null;
  EstadoPrestamo: string | null;
  IdContrato: string | null;
  DestinoPrestamo: string;
  UbicacionEquipo?: string | null;
  NombreGavetero?: string | null;
  NombreMueble?: string | null;
  UbicacionMueble?: string | null;
  AdministradorAmbiente?: string | null;
  TipoUsuario?: string | null;
  IdCarrera?: number | null;
  NombreMateria?: string | null;
  GrupoEquipoId?: number[] | null;
  Guardado?: boolean;
}
