import { BaseModel } from '@shared/model';
export class Equipos extends BaseModel {
  CodigoImt: number | null = null;
  CodigoUcb: string | null = null;
  NumeroSerial: string | null = null;
  EstadoEquipo: string | null = null;
  Ubicacion: string | null = null;
  IdAmbiente?: number | null = null;
  IdProcedencia?: number | null = null;
  CostoReferencia: number | null = null;
  Descripcion: string | null = null;
  Procedencia: string | null = null;
  NombreGrupoEquipo: string | null = null;
  IdGrupoEquipo: number | null = null;
  Modelo?: string | null = null;
  Marca?: string | null = null;
  NombreGavetero: string | null = null;
  IdGavetero?: number | null = null;
  FechaIngresoEquipo?: Date | null = null;
}
