import { BaseModel } from '@shared/model';
export class PrestamoDto extends BaseModel {
  CarnetUsuario: string | null = null;
  NombreUsuario: string | null = null;
  ApellidoPaternoUsuario: string | null = null;
  TelefonoUsuario: string | null = null;
  NombreGrupoEquipo: string | null = null;
  CodigoImt: string | null = null;
  CodigoUcb: string | null = null;
  NumeroSerial: string | null = null;
  FechaSolicitud: Date | null = null;
  FechaPrestamoEsperada: Date | null = null;
  FechaPrestamo: Date | null = null;
  FechaDevolucionEsperada: Date | null = null;
  FechaDevolucion: Date | null = null;
  Observacion: string | null = null;
  MotivoRechazo?: string | null = null;
  AutorizadoPor?: string | null = null;
  EntregadoPor?: string | null = null;
  EstadoPrestamo: string | null = null;
  UbicacionEquipo: string | null = null;
  NombreGavetero: string | null = null;
  NombreMueble: string | null = null;
  UbicacionMueble: string | null = null;
  AdministradorAmbiente: string | null = null;
  IdContrato: string | null = null;
  TipoUsuario: string | null = null;
  DestinoPrestamo: string | null = null;
  IdCarrera: number | null = null;
  NombreMateria: string | null = null;
  GrupoEquipoId: number[] = [];
  Guardado = false;
  constructor() {
    super();
    this.CarnetUsuario = null;
    this.NombreUsuario = null;
    this.ApellidoPaternoUsuario = null;
    this.TelefonoUsuario = null;
    this.NombreGrupoEquipo = null;
    this.CodigoImt = null;
    this.CodigoUcb = null;
    this.NumeroSerial = null;
    this.FechaSolicitud = null;
    this.FechaPrestamoEsperada = null;
    this.FechaPrestamo = null;
    this.FechaDevolucionEsperada = null;
    this.FechaDevolucion = null;
    this.Observacion = null;
    this.EstadoPrestamo = null;
    this.IdContrato = null;
    this.UbicacionEquipo = null;
    this.NombreGavetero = null;
    this.NombreMueble = null;
    this.UbicacionMueble = null;
    this.AdministradorAmbiente = null;
    this.TipoUsuario = null;
    this.DestinoPrestamo = null;
    this.IdCarrera = null;
    this.NombreMateria = null;
    this.GrupoEquipoId = [];
    this.Guardado = false;
  }
}
