import { BaseModel } from '@shared/model';
export class PrestamoDto extends BaseModel {
  CarnetUsuario: string | null = null;
  NombreUsuario: string | null = null;
  ApellidoPaternoUsuario: string | null = null;
  TelefonoUsuario: string | null = null;
  NombreGrupoEquipo: string | null = null;
  CodigoImt: string | null = null;
  FechaSolicitud: Date | null = null;
  FechaPrestamoEsperada: Date | null = null;
  FechaPrestamo: Date | null = null;
  FechaDevolucionEsperada: Date | null = null;
  FechaDevolucion: Date | null = null;
  Observacion: string | null = null;
  MotivoRechazo?: string | null = null;
  AutorizadoPor?: string | null = null;
  EntregadoPor?: string | null = null;
  EstadoPrestamo: string | null = null;
  Ubicacion_Equipo: string | null = null;
  Nombre_Gavetero: string | null = null;
  Nombre_Mueble: string | null = null;
  Ubicacion_Mueble: string | null = null;
  Administrador_Ambiente: string | null = null;
  IdContrato: string | null = null;
  TipoUsuario: string | null = null;
  DestinoPrestamo: string | null = null;
  IdCarrera: number | null = null;
  NombreMateria: string | null = null;
  constructor() {
    super();
    this.CarnetUsuario = null;
    this.NombreUsuario = null;
    this.ApellidoPaternoUsuario = null;
    this.TelefonoUsuario = null;
    this.NombreGrupoEquipo = null;
    this.CodigoImt = null;
    this.FechaSolicitud = null;
    this.FechaPrestamoEsperada = null;
    this.FechaPrestamo = null;
    this.FechaDevolucionEsperada = null;
    this.FechaDevolucion = null;
    this.Observacion = null;
    this.EstadoPrestamo = null;
    this.IdContrato = null;
    this.Ubicacion_Equipo = null;
    this.Nombre_Gavetero = null;
    this.Nombre_Mueble = null;
    this.Ubicacion_Mueble = null;
    this.Administrador_Ambiente = null;
    this.TipoUsuario = null;
    this.DestinoPrestamo = null;
    this.IdCarrera = null;
    this.NombreMateria = null;
  }
}
