begin;

alter table usuarios
    add column if not exists refresh_token text,
    add column if not exists refresh_token_expiry timestamp with time zone,
    add column if not exists bloqueado boolean not null default false,
    add column if not exists motivo_bloqueo text;

create index if not exists ix_usuarios_refresh_token
    on usuarios (refresh_token);

create table if not exists configuraciones_sistema (
    id_configuracion integer generated by default as identity,
    monto_minimo_contrato numeric(18, 2) not null,
    horario_inicio_minutos integer not null,
    horario_fin_minutos integer not null,
    nombre_jefe_carrera varchar(255) not null,
    firma_jefe_carrera_base64 text not null,
    tiempo_minimo_reserva_minutos integer not null,
    tiempo_recordatorio_previo_minutos integer not null,
    minutos_gracia_atraso integer not null,
    estado_eliminado boolean not null default false,
    constraint pk_configuraciones_sistema primary key (id_configuracion)
);

commit;
